ADSeek/Controllers/ActiveDirectoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ADSeek.Application.Interfaces.Services;
using ADSeek.Application.Requests;
using ADSeek.Domain.Models;
using ADSeek.Infrastructure.Mappers;
using ADSeek.Infrastructure.Services;
using ADSeek.Inputs;
using ADSeek.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Novell.Directory.Ldap;
using ActiveDirectoryObject = ADSeek.Domain.Models.ActiveDirectoryObject;

namespace ADSeek.Controllers
{
    public class ActiveDirectoryController : Controller
    {
        public static IActiveDirectoryService _service;
        private readonly IServiceProvider _provider;
        public static ActiveDirectoryObjectModel _me;
        private readonly IMapper _mapper;

        public ActiveDirectoryController(IServiceProvider provider, IMapper mapper)
        {
            _provider = provider;
            _mapper = mapper;
        }


        private ActiveDirectorySettings.ActiveDirectoryConnectionSettings _settings(string domain, string dn, string password)
        {
            return new ActiveDirectorySettings.ActiveDirectoryConnectionSettings()
            {
                Host = domain,
                Password = password,
                Port = 389,
                SSLEnabled = true,
                SSLPort = 636,
                Username = dn
            };
        }

        [HttpPost]
        public async Task<IActionResult> Authorize(ActiveDirectoryAuthorizationModel data)
        {
            string domain = data.Domain;
            
            string dn = data.DistinguishedName;
            string password = data.Password;

            LdapRequests.AuthorizeRequest request = new LdapRequests.AuthorizeRequest(dn, password);

            _service = new ActiveDirectoryService(_settings(domain, dn, password), new ActiveDirectoryConverter(), _mapper);

            ActiveDirectoryResult result = await _service.AuthorizeAsync(request);

            if (!result.IsOk)
            {
                ViewBag.ExceptionByAuthorization = result.ErrorMessage;

                return View("/Views/Home/Index.cshtml");
            }

            Session.CURRENT_USER = await _service.GetMeAsync();
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View("/Views/ActiveDirectoryUser/ActiveDirectoryUserView.cshtml", Session.CURRENT_USER);
        }

        [HttpGet]
        public async Task<IActionResult> UserView(string dn)
        {
            var neededObject = await _service.SearchAsync(new LdapRequests.SearchRequest(dn));

            var user = _mapper.Map<ActiveDirectoryUser>(neededObject.FirstOrDefault());

            return View("/Views/ActiveDirectoryUser/ActiveDirectoryUserView.cshtml", user);
        }
        
        [HttpGet]
        public async Task<IActionResult> GroupView(string dn)
        {
            var neededObject = await _service.SearchAsync(new LdapRequests.SearchRequest(dn));

            var group = _mapper.Map<ActiveDirectoryGroup>(neededObject.FirstOrDefault());

            return View("/Views/ActiveDirectoryGroup/ActiveDirectoryGroupView.cshtml", group);
        }
        
        [HttpGet]
        public async Task<IActionResult> ComputerView(string dn)
        {
            var neededObject = await _service.SearchAsync(new LdapRequests.SearchRequest(dn));

            var computer = _mapper.Map<ActiveDirectoryComputer>(neededObject.FirstOrDefault());

            return View("/Views/ActiveDirectoryComputer/ActiveDirectoryComputerView.cshtml", computer);
        }
        
        [HttpGet]
        public async Task<IActionResult> ObjectView(string dn)
        {
            var neededObject = await _service.SearchAsync(new LdapRequests.SearchRequest(dn));
            
            return View("/Views/ActiveDirectory/ActiveDirectoryObjectView.cshtml", neededObject.FirstOrDefault());
        }

        [HttpPost]
        public async Task<IActionResult> UploadUserPhoto(ActiveDirectoryUserPhotoUploadModel input)
        {
            var attributesToModify = new LdapAttributeSet();

            await using var memoryStream = new MemoryStream();
            memoryStream.Seek(0, SeekOrigin.Begin);

            await input.FormFile.CopyToAsync(memoryStream);

            attributesToModify.Add("photo", new("photo", memoryStream.ToArray()));

            var modifyRequest = new LdapRequests.ModifyRequest(input.DistinguishedName, attributesToModify);

            try
            {
                await _service.ModifyAsync(modifyRequest);
            }
            catch (Exception exception)
            {
                return View("/Views/Home/Error_View.cshtml", exception);
            }
            
            return RedirectToAction("UserView", new {dn = input.DistinguishedName});
        }

        [HttpGet]
        public async Task<IActionResult> Add_Object()
        {
            return View("Add_Object");
        }

        [HttpPost]
        public async Task<IActionResult> Add_Object(CreateUserInput model)
        {
            var cn = model.DisplayName;
            var dn = $"CN={cn},CN=Users,DC=OLEG,DC=local";
            dn = $"CN={cn},CN=Users,DC=dc,DC=sharipov-bulat,DC=ru";

            var attributes = new LdapAttributeSet();

            try
            {
                attributes = new LdapAttributeSet()
                {
                    new("objectClass", "user"),
                    new("initials", model.Initials),
                    new("displayName", model.DisplayName),
                    new("givenName", model.GivenName),
                    new("sn", model.Surname),
                    new("cn", cn),
                    new("sAMAccountName", model.AccountName),
                    new("mail", model.Mail)
                };
            }
            catch
            {
                ViewBag.ExceptionByCreation = "Для успешного создания объекта необходимо заполнить все поля";

                return View("Add_Object");
            }

            var request = new LdapRequests.CreateRequest(dn, attributes);

            var result = await _service.InsertAsync(request);
            
            var password = model.Password;

            var attributesToModify = new LdapAttributeSet()
            {
                new("pwdLastSet", "0"),
                new("unicodePwd", Encoding.Unicode.GetBytes($"\"{password}\"")),
                new("userAccountControl", "512")
            };
            
            var modifyRequest = new LdapRequests.ModifyRequest(dn, attributesToModify);

            var result2 = await _service.ModifyAsync(modifyRequest);

            if (model.Photo is not null)
            {       
                await using var memoryStream = new MemoryStream();
                memoryStream.Seek(0, SeekOrigin.Begin);

                await model.Photo.CopyToAsync(memoryStream);

                var photoAttributes = new LdapAttributeSet()
                {

                    new("photo", memoryStream.ToArray())
                };

                var photoRequest = new LdapRequests.ModifyRequest(dn, photoAttributes);

                await _service.ModifyAsync(photoRequest);
            }
            
            if (result.IsOk && result2.IsOk)
            {
                return RedirectToAction("UserView", new {dn = dn});
            }
            else
            {
                ViewBag.ExceptionByCreation = result.ErrorMessage;
                
                return View("Add_Object");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Search()
        {
            return View("ActiveDirectorySearch");
        }

        [HttpPost]
        public async Task<IActionResult> Search(ActiveDirectorySearchModel model)
        {
            try
            {
                string dn = model.DistinguishedName;
                string filter = model.Filter;

                var search_results = await _service.SearchAsync(new LdapRequests.SearchRequest(dn, filter));

                var dns = search_results.Select(item => (item.DistinguishedName, item.ObjectClass)).ToList();

                return View("/Views/ActiveDirectoryObjects/ActiveDirectorySearchResults.cshtml", new ActiveDirectoryObjectsListModel() { DistinguishedNames = dns});
            }
            catch (Exception e)
            {
                return View("/Views/Home/Error_View.cshtml");
            }
        }
    }
}

ADSeek/Controllers/ActiveDirectoryObjectsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ADSeek.Application.Interfaces.Services;
using ADSeek.Application.Requests;
using ADSeek.Domain.Models;
using ADSeek.Models;
using Microsoft.AspNetCore.Mvc;

namespace ADSeek.Controllers
{
    public class ActiveDirectoryObjectsController : Controller
    {
        private readonly IActiveDirectoryService _service;

        public ActiveDirectoryObjectsController()
        {
            _service = ActiveDirectoryController._service;
        }

        // private ActiveDirectoryObjectModel _convert(ActiveDirectoryObject adObj)
        // {
        //     return new ActiveDirectoryObjectModel()
        //     {
        //         Attributes = adObj.Attributes.Select(x => new ActiveDirectoryAttributeModel()
        //         {
        //             Attribute = x.Key,
        //             Value = string.Join(",", x.Value.StringValueArray)
        //         }).ToList()
        //     };
        // }
        //
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            try
            {
                var targetOu = $"CN=Users,DC={(string.Join(",DC=", _service.Settings.Host.Split(".")))}";
                
                var objects = await _service.SearchAsync(new LdapRequests.SearchRequest(targetOu));

                var dns = objects.Select(x => (x.DistinguishedName, x.ObjectClass)).ToList();
        
                var o = new ActiveDirectoryObjectsListModel()
                {
                    DistinguishedNames = dns
                };
             
                return View("ActiveDirectoryObjectsList", o);
            }
            catch (Exception e)
            {
                return View("/Views/Home/Error_View.cshtml", e);
            }
        }
    }
}

ADSeek/Views/Shared/ActiveDirectoryUserPhotoUpload.cshtml
@model ActiveDirectoryUserPhotoUploadModel

 
    <form enctype="multipart/form-data" method="post" asp-controller="ActiveDirectory" asp-action="UploadUserPhoto">
    @Html.HiddenFor(model => model.DistinguishedName)   
        <input asp-for="FormFile" type="file">
        <input class="btn btn-dark" type="submit" value="Загрузить фото">
    </form>                                          

ADSeek/Views/Shared/AuthorizeForm.cshtml
@model ActiveDirectoryAuthorizationModel

@{
    string exception = ViewBag.ExceptionByAuthorization;
}

@using (Html.BeginForm("Authorize", "ActiveDirectory", FormMethod.Post))
{
    <div>
        <table>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Domain)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.EditorFor(model => model.Domain, new {htmlAttributes = new {@class = "form-control"}})
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.DistinguishedName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.EditorFor(model => model.DistinguishedName, new {htmlAttributes = new {@class = "form-control"}})
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.Password)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.PasswordFor(model => model.Password, new {@class = "form-control"})
                </td>
            </tr>
            <tr>
                <td>
                    <input id="send_data" type="submit" value="Авторизация" oninput="hide()" class="btn btn-dark"/>
                </td>
            </tr>
            @if (!string.IsNullOrEmpty(exception))
            {
                <tr>
                    <td>
                        <span id="span_exc" style="color: red" >
                            @exception
                        </span>
                    </td>
                </tr>
            }
        </table>
    </div>
}

<script>    

    window.onload = (event) => {
      console.log("page is fully loaded");
      hide();
    };

    function hide() {
            setTimeout(() => {
                        console.log('feri');
                          
                        const box = document.getElementById('span_exc');
                    
                        // 👇️ removes element from DOM
                        box.style.display = 'none';
                    
                        // 👇️ hides element (still takes up space on page)
                        // box.style.visibility = 'hidden';
                      }, 3000);
    }
          
        
    
</script>

ADSeek/Views/Shared/_Layout.cshtml
@{
    bool isAuthorized = Session.IS_AUTHORIZED;
    string account = Session.CURRENT_USER?.DisplayName;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - ADSeek</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">ADSeek</a>
                    </li>
                    @if (isAuthorized)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ActiveDirectoryObjects" asp-action="Index">Объекты домена</a>
                        </li>
                        if (Session.IS_DOMAIN_ADMINISTRATOR)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ActiveDirectory" asp-action="Add_Object">Добавить учетную запись</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ActiveDirectory" asp-action="Search">Поиск</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ActiveDirectory" asp-action="Index" asp-route-dn="@account">Аккаунт</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Exit">Выйти</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">ADSeek</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>